//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductStockApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ClientsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientsTable()
        {
            this.SalesTable = new HashSet<SalesTable>();
        }
    
        public int ClientID { get; set; }

        [Required(ErrorMessage ="Lütfen Müþteri adý kýsmýný boþ býrakmayýnýz.")]
        [StringLength(50, ErrorMessage ="Maksimum 50 karakter kullanabilirsiniz.")]
        public string ClientName { get; set; }

        [Required(ErrorMessage = "Lütfen Müþteri soyadý kýsmýný boþ býrakmayýnýz.")]
        [StringLength(50, ErrorMessage = "Maksimum 50 karakter kullanabilirsiniz.")]
        public string ClientSurname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesTable> SalesTable { get; set; }
    }
}
