//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductStockApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductsTable()
        {
            this.SalesTable = new HashSet<SalesTable>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Brand { get; set; }
        public Nullable<short> ProductCategory { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<byte> Amount { get; set; }
    
        public virtual CategoriesTable CategoriesTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesTable> SalesTable { get; set; }
    }
}
