//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductStockApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTable
    {
        public int SalesID { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Client { get; set; }
        public Nullable<byte> Amount { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ClientsTable ClientsTable { get; set; }
        public virtual ProductsTable ProductsTable { get; set; }
    }
}
